version: "3"

volumes:
  static-content:

services:
  nodejs:
    container_name: nodejs
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=America/New_York
    ports:
      - 3000:3000
    volumes:
      - static-content:/usr/src/app
  nginx:
    container_name: nginx
    image: nginx
    # build:
    #   context: .
    #   dockerfile: Dockerfile.nginx
    environment:
      - TZ=America/New_York
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static-content:/var/www/public
    depends_on:
      - nodejs
